# Nixarchy desktop (Omarchy vendored for NixOS): Hyprland + QuickShell shell.
# The nixarchy module mkDefaults sddm (theme "omarchy"), portals, PipeWire,
# printing, NetworkManager etc.; this file only adds what it does not cover.
{
  services.keytao-app.enable = true;

  programs.nixarchy = {
    enable = true;
    # nixarchy-apply copies the Install menu's app selection into this flake
    # as nixarchy-apps.nix before rebuilding.
    flake = "/home/rea/nix-config";
    # Desktop user: adds the `input` group (upstream installer runs usermod -aG input).
    user = "rea";
  };

  # App selection generated by the Omarchy Install menu (nixarchy-apply
  # overwrites it at the flake root on every apply).
  imports = [ ../../nixarchy-apps.nix ];

  # Autologin straight into the Omarchy session; the module itself does not
  # pick a default session. Session id stays "omarchy" (upstream convention).
  services.displayManager.defaultSession = "omarchy";
  services.displayManager.autoLogin = {
    enable = true;
    user = "rea";
  };

  programs.kdeconnect.enable = true;
  programs.dconf.enable = true;

  # Nautilus (Omarchy's default file manager) needs gvfs for trash/mounts.
  services.gvfs.enable = true;

  services.power-profiles-daemon.enable = true;
  services.upower.enable = true;

  # NVIDIA-specific env vars needed at session level (carried over from linux-kde.nix).
  environment.sessionVariables = {
    LIBVA_DRIVER_NAME = "nvidia";
    __GLX_VENDOR_LIBRARY_NAME = "nvidia";
    NVD_BACKEND = "direct";
  };
}
